language: python
sudo: false
services:
  - redis-server
python:
  - "2.7"
install:
  - make travis
  - pip install tox codecov
script: tox -- --with-coverage --cover-xml --cover-package=push_processor
after_success:
  - codecov
